runtime: python
service: api
env: flex

runtime_config:
  python_version: 3

entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10